name: lastfm collage generator

on:
    push:
        branches:
            - master
    schedule:
        - cron: "0 0 * * *"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: Install dependencies
          run: python -m pip install --upgrade pip setuptools wheel lastfm_cg
        - name: Install lastfm_cg
          run: lastfm_cg -d -u d_beley -r 2 -c 8 -t 1month --API_KEY ${{ secrets.LASTFM_API_KEY }} --API_SECRET ${{ secrets.LASTFM_API_SECRET }} --output_filename lastfm.png
        - name: Commit new image
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: 'Action: Update lastfm.png.'
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
